version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "test-awsms-poc"
          ContainerPort: 5030
          PlatformVersion: "LATEST"
           NetworkConfiguration:
            AwsvpcConfiguration:
              Subnets: ["subnet-0243c2eef169cefd4", "subnet-00ffd514686eafe97"]
              SecurityGroups: ["sg-0dc268f0a643b1bce"]
              AssignPublicIp: "ENABLED"
Hooks:
- BeforeInstall: "BeforeInstallHookFunctionName"
- AfterInstall: "AfterInstallHookFunctionName"
- AfterAllowTestTraffic: "AfterAllowTestTrafficHookFunctionName"
- BeforeAllowTraffic: "BeforeAllowTrafficHookFunctionName"
- AfterAllowTraffic: "AfterAllowTrafficHookFunctionName"
