version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:160357565307:task-definition/my-new-task:1"
        LoadBalancerInfo:
          ContainerName: "test-awsms-poc"
          ContainerPort: 5030
          PlatformVersion: "LATEST"
