version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "test-awsms-poc"
          ContainerPort: 5030
          PlatformVersion: "LATEST"
           NetworkConfiguration:
            AwsvpcConfiguration:
              Subnets: ["subnet-022e892622fe90c8e", "subnet-06a409c9a36a9848c"]
              SecurityGroups: ["sg-0dc268f0a643b1bce"]
              AssignPublicIp: "DISABLED"
